name: Unity Error Check
on:
  pull_request:  # プルリクエスト時にフックして動作
  workflow_dispatch: # 手動実行

jobs:
  Check:
    #Self-Hosted Runnerで動かす
    runs-on: self-hosted

    # 手順
    steps:

    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
        lfs: false

    # Unityを開く(エラーチェック)
    - name: OpenUnity
      run: ${{ env.UNITY_EDITOR_PATH }} -quit -batchmode -projectPath ${{ secrets.UNITY_PROJECT_PATH }}
      shell: cmd

    # Discordに通知する
    - name: PostMessage
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
        SHA: ${{ github.sha }}
        ACTOR: ${{ github.actor }}
        TEXT: "Success"
      run:
        Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"${{ env.TEXT }} :_sikei_:\r${{ env.PULL_REQUEST_URL }}\r`"}" ${{ env.DISCORD_WEBHOOK_URL }}