name: Unity Error Check
on:
  pull_request:  # プルリクエスト時にフックして動作
  workflow_dispatch: # 手動実行

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UNITY_EDITOR_PATH: ${{ vars.UNITY_EDITOR_PATH }}
  UNITY_PROJECT_PATH: ${{ vars.UNITY_PROJECT_PATH }}
  PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
  SHA: ${{ github.sha }}
  ACTOR: ${{ github.actor }}
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  Check:
    #Self-Hosted Runnerで動かす
    runs-on: self-hosted

    # 手順
    steps:

    # チェックアウト
    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false
        lfs: false

    # Unityを開く(エラーチェック)
    - name: OpenUnity
      run: ${{ env.UNITY_EDITOR_PATH }} -quit -batchmode -projectPath ${{ env.UNITY_PROJECT_PATH }}
      shell: cmd

    # Discordに通知する（失敗時のみ）
    - name: PostMessage
      if: failure()
      run: |
        Invoke-WebRequest -Uri ${{ env.DISCORD_WEBHOOK_URL }} -Method Post -Headers @{"Content-Type"="application/json"} -Body '{"content":"${{ env.PULL_REQUEST_URL }}"}'
      shell: pwsh